=== FranPaton/repositorio_daw/repo_lmsgi/Boletin Unidad 3 XSD/Ejercicio12/ejerc12.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="expresiones">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="expresion" maxOccurs="unbounded">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="Capitulo[0-9]" />
                            <xs:pattern value="Capitulo[1-9]?[0-9]" />
                            <xs:pattern value="Capitulo[1-9][0-9]?" />
                            <xs:pattern value="(Capitulo )([0]|[1-9][0-9]*)" />
                            <xs:pattern value="[^0-9][Z]" />
                            <xs:pattern value="ABB+C"/>
                            <xs:pattern value="RS{2,}[3-8]?"/>
                            <xs:pattern value="COD[0-9]{3}.+"/>
                            
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== FranPaton/repositorio_daw/repo_lmsgi/Boletin Unidad 3 XSD/Ejercicio12/ejerc12.xml
<?xml version="1.0" encoding="UTF-8"?>
<expresiones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ejerc12.xsd">
    <expresion>Capitulo0</expresion>
    <expresion>Capitulo10</expresion>
    <expresion>Capitulo10</expresion>
    <expresion>Capitulo 0</expresion>
    <expresion>ZZ</expresion>
    <expresion>ABBC</expresion>
    <expresion>RSSSSSS7</expresion>
    <expresion>COD122assad</expresion>

</expresiones>
